### ISSUE TITLE
DraggablePanel and VideoPlayer usage generates some empty spaces between dragged view and second view.

### ISSUE THREAD

**Issue by jayachandrak** [pedrovgs/DraggablePanel#12]
Added two fragments to DraggablePanel 
one is Video player second one is list fragment 

while maximizing the view, videoview is getting moved slightly  then it will have some empty space in corners 
its not happening with normal views like images its happening only while playing video

**Comment by manpreetsinghsodhi** [comment]
i guess same is happening in my case. On maximising vedioview, bottom fragment is slighly moving under vedioview and lot of empty spaces can been seen. Since in my case i am using listview behind draggable panel so list view is visible . please help

**Comment by pedrovgs** [comment]
@jayachandrakuruba we are trying to fix this issue, but I need to see your code to help you. My demo is working find :S. Can you give me access to your repository to take a look?

FYI, I'll try to fix a similar issue reported by @manpreetsinghsodhi.

**Comment by pedrovgs** [comment]
@jayachandrakuruba I've released a new version (Release 1.3) with some fixes. Can you review if your I've fixed your problem with this release?

**Comment by jayachandrak** [comment]
Sure i will test and let you know the result

Is this version supports oriantation changes?

**Comment by pedrovgs** [comment]
@jayachandrakuruba I'm working to support orientation changes. Release 1.3 is working fine for you?

**Comment by pedrovgs** [comment]
@jayachandrakuruba can you check if this branch or the previous release fix your problem? https://github.com/pedrovgs/DraggablePanel/tree/fix-video-view-sample-problems

**Comment by jayachandrak** [comment]
I have tested it wasn't fixed my problem , are you supporting orientation
changes?

**Comment by Fiddl3** [comment]
this https://github.com/Fiddl3/DraggablePanel/commit/ba33447ae423c3fa6ca4083fbb456d924eea6274 implementation of `onLayout` method should fix this issue.

**Comment by pedrovgs** [comment]
@jayachandrakuruba can you upload a screenshot or video to review your problem?

**Comment by Fiddl3** [comment]
This happens when VideoView change his size to match played Video aspect ratio.
One of solution is put VideoView in container ex `FrameLayout` in that case video size changes will not affect dragView height.

**Comment by ppamorim** [comment]
VideoPlayer extends SurfaceView, SurfaceView can't be transformed or resized. 
I recommend to change to TextureView.
Look to this sample: https://github.com/ppamorim/DraggablePanel/tree/textureViewSample

**Comment by Fiddl3** [comment]
SurfaceView can be resized (can not be animated, transformed and scaled).
TextureView can only be used in a H/A windows.
TextureView use more memory, much more.
TextureView has small lag, needs 1-5 extra frames to update

So for video playback we should use overridden SV, add listeners and update SV dimensions manually when it's necessary. TV will not work on all devices (ex. wo H/A, with small amount of RAM memory....)... but it's easier to implement 

EDIT
H/A - Hardware Acceleration

**Comment by ppamorim** [comment]
@Fiddl3 Correct! I confuse me with resized and scaled.
But the scale of SurfaceView as some problems (black borders while dragging).

**Comment by Fiddl3** [comment]
If you take care of its size (while dragging) there will not be black borders. It takes some time, but it can be done.

**Comment by ppamorim** [comment]
I've removed the surfaceView if my project because it cause some problems(black screen, resize/scale)

**Comment by Fiddl3** [comment]
...and if everything works well for you, that's the most effective way, but you have to make sure that app is working as supposed on all devices you targeting - that's the main goal

**Comment by pedrovgs** [comment]
@Fiddl3 is this issue related just to VideoPlayer?

**Comment by Fiddl3** [comment]
It's related to all view all which were not designed to move/resize/transform while rendering. But we can't do anything to improve this in library.

**Comment by pedrovgs** [comment]
Ok, thanks for your help!

**Comment by ppamorim** [comment]
@Fiddl3 API 14 here :p
